IGNORE_CONFIG_FILE: false

activeBendingSettings:
  shouldBendingMenuRender: true
bendingCycleAlpha: 0.75
chiBarAlpha: 0.5
chiBarSettings:
  shouldChiNumbersRender: true
  shouldChibarRender: true
displayGetBendingMessage: true
nameConflicts:
  explosive_pillar: false
  slipstream: false
  inferno_punch: false
  sandstorm: false
  cleanse: false
  purify: false
  ice_prison: false
  wave: false
  ravine: false
  air_gust: false
  lightning_spear: false
  sand_prison: false
  pickup_block: false
  air_bubble: false
  lightning_redirect: false
  flamethrower: false
  water_cannon: false
  fireball: false
  boulder_ring: false
  ice_burst: false
  lightning_arc: false
  air_burst: false
  fire_arc: false
  restore: false
  water_bubble: false
  cloudburst: false
  water_arc: false
  airblade: false
  explosion: false
  light_fire: false
  lightning_raze: false
  air_jump: false
  water_skate: false
  fire_jump: false
  mine_blocks: false
  wall: false
  earthspike: false
nameKeymappings:
  ice_prison: 49
radialMenuAlpha: 0.75
shaderSettings:
  useCleanseShaders: false
  usePurifyShaders: false
  useRestoreShaders: false
  useSlipstreamShaders: false
useCustomParticles: true
